"""Aurora combat Cog backed by the locked 16.17.1 champion sources."""

from __future__ import annotations

from dataclasses import replace
from decimal import ROUND_HALF_EVEN, Decimal

from lol_build.cogs.base import (
    DUEL_CAPABILITIES,
    ActionPlan,
    CastBlockWindow,
    ChampionCog,
    CogMaturity,
    ControlType,
    ParticipantContext,
    ReactionPlan,
)
from lol_build.cogs.mechanics import action, crowd_control, damage, healing, movement_speed
from lol_build.core.combat import DamageType
from lol_build.core.timeline import ActionChannel, ActionEvent, DamageOutput, StatusOutput


class AuroraCog(ChampionCog):
    """Model Aurora's Q5/E5/W1/R2 level-13 single-target fixture.

    The fixed rotation lands Between Worlds, both halves of Twofold Hex, and
    The Weirding before continuing with ordinary attacks. Every third modeled
    hit exorcises one spirit. Each spirit deals its maximum-health proc once,
    heals once per second for four seconds, and contributes its locked movement
    bonus while active. Geometry and runtime hit validation remain blockers.
    """

    maturity = CogMaturity.MODELED_UNVERIFIED
    capabilities = DUEL_CAPABILITIES
    evidence_refs = (
        "data/raw/16.17.1/en_US/champion/Aurora.json",
        "data/raw/16.17.1/communitydragon/champions/893.json",
        "data/raw/16.17.1/communitydragon/champions/aurora.bin.json",
    )

    _R_AT_MS = 100
    _W_AT_MS = 250
    _Q_AT_MS = 500
    _E_AT_MS = 850
    _Q_RETURN_DELAY_MS = 550
    _FIRST_ATTACK_AT_MS = 1350
    _SPIRIT_DURATION_MS = 4000

    @staticmethod
    def _cooldown_ms(base_seconds: Decimal, ability_haste: Decimal) -> int:
        """Apply the standard ability-haste divisor to a locked cooldown.

        :param base_seconds: Rank-specific cooldown measured in seconds.
        :param ability_haste: Non-negative haste from Aurora's snapshot.
        :return: Positive cooldown rounded to the nearest-even millisecond.
        :raises ValueError: If either cooldown input is negative.
        """
        if base_seconds < 0 or ability_haste < 0:
            raise ValueError("cooldown inputs cannot be negative")
        milliseconds = base_seconds * Decimal(100_000) / (Decimal(100) + ability_haste)
        return max(1, int(milliseconds.to_integral_value(ROUND_HALF_EVEN)))

    @staticmethod
    def _spirit_heal(level: int, ability_power: Decimal) -> Decimal:
        """Evaluate one locked Spirit Abjuration healing tick.

        :param level: Aurora's champion level on the one-to-eighteen curve.
        :param ability_power: Aggregated ability power used by the heal ratio.
        :return: Raw healing generated by one active spirit per second.
        """
        bounded = min(18, max(1, level))
        base = Decimal(3) + Decimal(17) * Decimal(bounded - 1) / Decimal(17)
        return base + Decimal("0.02") * ability_power

    @staticmethod
    def _spirit_damage_ratio(ability_power: Decimal) -> Decimal:
        """Evaluate the passive's target-maximum-health damage fraction.

        :param ability_power: Aggregated ability power used by the proc ratio.
        :return: Fraction of target maximum health dealt as magic damage.
        """
        return Decimal("0.01") + Decimal("0.00027") * ability_power

    @staticmethod
    def _base_spirit_speed_ratio(level: int, ability_power: Decimal) -> Decimal:
        """Evaluate movement speed supplied by the first active spirit.

        :param level: Aurora's champion level on the locked breakpoint curve.
        :param ability_power: Aggregated ability power used by the speed ratio.
        :return: Fractional movement-speed bonus for the first spirit.
        """
        bounded = min(18, max(1, level))
        return (
            Decimal("0.05")
            + Decimal("0.002") * Decimal(bounded - 1)
            + Decimal("0.0003") * ability_power
        )

    @staticmethod
    def _additional_spirit_speed_ratio(ability_power: Decimal) -> Decimal:
        """Evaluate movement speed contributed by each additional spirit.

        :param ability_power: Aggregated ability power used by the speed ratio.
        :return: Fractional movement-speed bonus for an extra active spirit.
        """
        return Decimal("0.02") + Decimal("0.00015") * ability_power

    def engagement_speed_multiplier(self, context: ParticipantContext) -> Decimal:
        """Expose W1's locked Realm Hopper movement bonus.

        Passive movement requires prior target interaction and is deliberately
        excluded from the pre-contact engagement metric.

        :param context: Role-bound Aurora encounter context.
        :return: Rank-one Across the Veil movement-speed multiplier.
        """
        return Decimal("1.20")

    def engagement_dash_distance(self, context: ParticipantContext) -> Decimal:
        """Expose Across the Veil's locked directional hop distance.

        :param context: Role-bound Aurora encounter context.
        :return: Rank-independent W displacement in game units.
        """
        return Decimal(300)

    def item_candidate_blocker(self, item: dict[str, object]) -> str | None:
        """Reject item channels absent from Aurora's fixed event policy.

        AP, attack speed, haste, health, resistances, penetration, and movement
        reach represented combat or engagement channels. Mana limits, critical
        strikes, and generic sustain amplification are not inferred.

        :param item: Normalized candidate from the locked item catalog.
        :return: Aurora-scoped blocker, or ``None`` for represented channels.
        """
        stats = item["stats"]
        assert isinstance(stats, dict)
        unsupported = {
            "CRITICAL_STRIKE_CHANCE",
            "MANA",
            "MANA_REGEN",
        } & stats.keys()
        if unsupported:
            names = ",".join(sorted(unsupported))
            return f"AURORA_ITEM_STAT_NOT_MODELED:{item['id']}:{names}"
        return None

    def _q_events(self, context: ParticipantContext) -> tuple[ActionEvent, ...]:
        """Schedule both halves of every legal rank-five Twofold Hex cast.

        The return uses its unamplified value because current target health is a
        timeline state unavailable while action plans are assembled.

        :param context: Snapshot supplying AP, haste, duration, and role IDs.
        :return: Outgoing and returning Q damage events inside the horizon.
        """
        cooldown_ms = self._cooldown_ms(Decimal(7), context.snapshot.ability_haste)
        amount = Decimal(145) + Decimal("0.40") * context.snapshot.ability_power
        base = self._sequence_base(context) + 100
        events: list[ActionEvent] = []
        cast_at_ms = self._Q_AT_MS
        cast_index = 1
        while cast_at_ms <= context.duration_ms:
            events.append(
                action(
                    f"AURORA_Q_TWOFOLD_HEX_OUT_{cast_index}",
                    at_ms=cast_at_ms,
                    sequence=base + cast_index * 10,
                    source=context.self_entity,
                    channel=ActionChannel.ABILITY,
                    outputs=(damage(context.opponent_entity, amount, DamageType.MAGIC),),
                )
            )
            return_at_ms = cast_at_ms + self._Q_RETURN_DELAY_MS
            if return_at_ms <= context.duration_ms:
                events.append(
                    action(
                        f"AURORA_Q_TWOFOLD_HEX_RETURN_{cast_index}",
                        at_ms=return_at_ms,
                        sequence=base + cast_index * 10 + 1,
                        source=context.self_entity,
                        channel=ActionChannel.ABILITY,
                        outputs=(damage(context.opponent_entity, amount, DamageType.MAGIC),),
                    )
                )
            cast_at_ms += cooldown_ms
            cast_index += 1
        return tuple(events)

    def _basic_attacks(self, context: ParticipantContext) -> tuple[ActionEvent, ...]:
        """Schedule ordinary attacks through the shared cadence helper.

        :param context: Snapshot supplying post-item attack speed and total AD.
        :return: Chronological blind-susceptible physical attacks.
        """
        interval_ms = self._attack_interval_ms(context.snapshot.attack_speed)
        base = self._sequence_base(context) + 300
        events: list[ActionEvent] = []
        at_ms = self._FIRST_ATTACK_AT_MS
        while at_ms <= context.duration_ms:
            events.append(
                action(
                    f"AURORA_BASIC_ATTACK_{len(events) + 1}",
                    at_ms=at_ms,
                    sequence=base + len(events),
                    source=context.self_entity,
                    channel=ActionChannel.BASIC_ATTACK,
                    outputs=(
                        damage(
                            context.opponent_entity,
                            context.snapshot.attack_damage,
                            DamageType.PHYSICAL,
                        ),
                    ),
                )
            )
            at_ms += interval_ms
        return tuple(events)

    def _apply_spirit_abjuration(
        self,
        context: ParticipantContext,
        events: tuple[ActionEvent, ...],
    ) -> tuple[ActionEvent, ...]:
        """Attach three-hit spirit procs and their deterministic healing ticks.

        Static attachment keeps the proc on its triggering action so control
        cancellation removes its immediate damage and speed. Separate healing
        ticks represent each spirit's four-second lifetime; blockers disclose
        that canceled prior hits do not rewind this precomputed tracker.

        :param context: Snapshot supplying AP, level, target health, and roles.
        :param events: Complete action schedule before passive processing.
        :return: Events enriched with passive procs and spirit healing ticks.
        """
        damaging = tuple(
            sorted(
                (
                    event
                    for event in events
                    if any(isinstance(output, DamageOutput) for output in event.outputs)
                ),
                key=lambda event: (event.at_ms, event.sequence, event.id),
            )
        )
        proc_events: list[ActionEvent] = []
        proc_times: list[int] = []
        proc_ids: set[str] = set()
        heal_amount = self._spirit_heal(context.snapshot.level, context.snapshot.ability_power)
        proc_damage = context.opponent_snapshot.max_hp * self._spirit_damage_ratio(
            context.snapshot.ability_power
        )
        for hit_index, event in enumerate(damaging, start=1):
            if hit_index % 3:
                continue
            proc_times.append(event.at_ms)
            proc_ids.add(event.id)
            for tick in range(1, 5):
                tick_at_ms = event.at_ms + tick * 1000
                if tick_at_ms > context.duration_ms:
                    break
                proc_events.append(
                    action(
                        f"AURORA_PASSIVE_SPIRIT_{len(proc_times)}_HEAL_{tick}",
                        at_ms=tick_at_ms,
                        sequence=self._sequence_base(context) + 500 + len(proc_events),
                        source=context.self_entity,
                        channel=ActionChannel.PASSIVE,
                        outputs=(healing(context.self_entity, heal_amount),),
                        requires_living_opponent=False,
                    )
                )

        enriched: list[ActionEvent] = []
        proc_index = 0
        for event in events:
            if event.id not in proc_ids:
                enriched.append(event)
                continue
            proc_index += 1
            prior_active = sum(
                event.at_ms - prior < self._SPIRIT_DURATION_MS
                for prior in proc_times[: proc_index - 1]
            )
            speed_ratio = (
                self._base_spirit_speed_ratio(
                    context.snapshot.level, context.snapshot.ability_power
                )
                if prior_active == 0
                else self._additional_spirit_speed_ratio(context.snapshot.ability_power)
            )
            enriched.append(
                replace(
                    event,
                    outputs=(
                        *event.outputs,
                        damage(context.opponent_entity, proc_damage, DamageType.MAGIC),
                        StatusOutput(
                            context.self_entity,
                            f"AURORA_SPIRIT_STACK_{prior_active + 1}",
                            self._SPIRIT_DURATION_MS,
                        ),
                        movement_speed(
                            context.self_entity,
                            context.snapshot.move_speed * speed_ratio,
                            duration_ms=self._SPIRIT_DURATION_MS,
                        ),
                    ),
                )
            )
        return tuple(
            sorted(
                (*enriched, *proc_events),
                key=lambda event: (event.at_ms, event.sequence, event.id),
            )
        )

    def build_action_plan(self, context: ParticipantContext) -> ActionPlan:
        """Build Aurora's locked Q5/E5/W1/R2 single-target action plan.

        :param context: Role-bound Aurora and opponent combat snapshots.
        :return: Spells, attacks, spirit procs, healing, movement, and blockers.
        """
        base = self._sequence_base(context)
        ap = context.snapshot.ability_power
        fixed = (
            action(
                "AURORA_R_BETWEEN_WORLDS_IMPACT",
                at_ms=self._R_AT_MS,
                sequence=base,
                source=context.self_entity,
                channel=ActionChannel.ABILITY,
                outputs=(
                    damage(
                        context.opponent_entity,
                        Decimal(275) + Decimal("0.70") * ap,
                        DamageType.MAGIC,
                    ),
                    crowd_control(
                        context.opponent_entity,
                        "SLOW",
                        duration_ms=2000,
                        magnitude=Decimal("0.30"),
                    ),
                    StatusOutput(context.self_entity, "AURORA_R_REALM_HOPPER", 4250),
                ),
            ),
            action(
                "AURORA_W_ACROSS_THE_VEIL",
                at_ms=self._W_AT_MS,
                sequence=base + 1,
                source=context.self_entity,
                channel=ActionChannel.MOVEMENT,
                outputs=(
                    StatusOutput(context.self_entity, "AURORA_W_INVISIBLE", 1000),
                    movement_speed(
                        context.self_entity,
                        context.snapshot.move_speed * Decimal("0.20"),
                        duration_ms=1000,
                    ),
                ),
                requires_living_opponent=False,
            ),
            action(
                "AURORA_E_THE_WEIRDING",
                at_ms=self._E_AT_MS,
                sequence=base + 2,
                source=context.self_entity,
                channel=ActionChannel.ABILITY,
                outputs=(
                    damage(
                        context.opponent_entity,
                        Decimal(230) + Decimal("0.70") * ap,
                        DamageType.MAGIC,
                    ),
                    crowd_control(
                        context.opponent_entity,
                        "SLOW",
                        duration_ms=1000,
                        magnitude=Decimal("0.80"),
                    ),
                    StatusOutput(context.self_entity, "AURORA_E_BACK_HOP", 1),
                ),
            ),
        )
        level_blockers = (
            ()
            if context.snapshot.level == 13
            else (f"AURORA_MODEL_LEVEL_UNSUPPORTED:{context.snapshot.level}",)
        )
        events = self._apply_spirit_abjuration(
            context,
            tuple(
                sorted(
                    (*fixed, *self._q_events(context), *self._basic_attacks(context)),
                    key=lambda event: (event.at_ms, event.sequence, event.id),
                )
            ),
        )
        return ActionPlan(
            "aurora_q5_e5_w1_r2_level13_spirit_fixture_v1",
            events,
            (
                *level_blockers,
                "AURORA_LEVEL13_Q5_E5_W1_R2_POLICY_UNVERIFIED",
                "AURORA_CAST_PROJECTILE_AND_HIT_TIMING_UNVERIFIED",
                "AURORA_PASSIVE_STATIC_HIT_TRACKER_DOES_NOT_REWIND_ON_CANCELLATION",
                "AURORA_PASSIVE_SPIRIT_HEAL_TICK_TIMING_UNVERIFIED",
                "AURORA_PASSIVE_HEAL_EVENTS_NOT_CAUSALLY_CANCELLED",
                "AURORA_PASSIVE_SPIRIT_OVERLAP_AND_SPEED_STACKING_UNVERIFIED",
                "AURORA_Q_RETURN_MISSING_HEALTH_AMPLIFICATION_NOT_MODELED",
                "AURORA_Q_RETURN_PATH_AND_MULTI_TARGET_REDUCTION_NOT_MODELED",
                "AURORA_W_INVISIBILITY_TARGETING_EFFECTS_NOT_MODELED",
                "AURORA_W_TERRAIN_CROSSING_NOT_MODELED",
                "AURORA_W_TAKEDOWN_RESET_NOT_MODELED",
                "AURORA_E_BACK_HOP_POSITION_NOT_MODELED",
                "AURORA_R_ZONE_CROSSING_AND_TELEPORT_NOT_MODELED",
                "AURORA_R_MULTI_TARGET_EFFECTS_NOT_MODELED",
                "AURORA_MANA_BUDGET_NOT_MODELED",
            ),
        )

    def build_reaction_plan(self, context: ParticipantContext) -> ReactionPlan:
        """Expose E and R movement control without inventing zone crossings.

        :param context: Role-bound snapshots identifying Aurora's opponent.
        :return: Initial R and E slows with explicit zone-control blockers.
        """
        return ReactionPlan(
            "aurora_e5_r2_slow_reaction_v1",
            cast_block_windows=(
                CastBlockWindow(
                    "aurora_r_initial_slow",
                    self._R_AT_MS,
                    min(self._R_AT_MS + 2000, context.duration_ms),
                    (ActionChannel.MOVEMENT,),
                    "AURORA_R_BETWEEN_WORLDS_IMPACT",
                    True,
                    ControlType.SLOW,
                ),
                CastBlockWindow(
                    "aurora_e_decaying_slow",
                    self._E_AT_MS,
                    min(self._E_AT_MS + 1000, context.duration_ms),
                    (ActionChannel.MOVEMENT,),
                    "AURORA_E_THE_WEIRDING",
                    True,
                    ControlType.SLOW,
                ),
            ),
            blockers=(
                "AURORA_E_SLOW_DECAY_SIMPLIFIED_TO_FIXED_WINDOW",
                "AURORA_R_ZONE_CROSSING_AND_TELEPORT_NOT_MODELED",
                "AURORA_R_ZONE_GEOMETRY_AND_MULTI_TARGET_NOT_MODELED",
                "AURORA_W_INVISIBILITY_REACTION_NOT_MODELED",
            ),
        )
