"""Fiora combat Cog backed by the locked 16.17.1 champion sources."""

from __future__ import annotations

from decimal import Decimal

from lol_build.cogs.base import (
    DUEL_CAPABILITIES,
    ActionPlan,
    CastBlockWindow,
    ChampionCog,
    CogMaturity,
    ControlImmunityWindow,
    ControlType,
    ParticipantContext,
    ReactionPlan,
)
from lol_build.cogs.mechanics import action, crowd_control, damage, healing
from lol_build.core.combat import DamageType
from lol_build.core.timeline import ActionChannel, ActionEvent, DamageModifierWindow, StatusOutput


class FioraCog(ChampionCog):
    """Model Fiora's Q5/W1/E5/R2 level-13 single-target duel fixture.

    Grand Challenge supplies four deterministic vital hits so the model can
    evaluate Duelist's Dance without inventing target-facing geometry. Riposte
    uses a fixed defensive interval followed by its non-stun stab variant.
    """

    maturity = CogMaturity.MODELED_UNVERIFIED
    capabilities = DUEL_CAPABILITIES
    evidence_refs = (
        "data/raw/16.17.1/en_US/champion/Fiora.json",
        "data/raw/16.17.1/communitydragon/champions/114.json",
        "data/raw/16.17.1/communitydragon/champions/fiora.bin.json",
    )

    _ATTACK_SPEED_RATIO = Decimal("0.69")
    _E5_ATTACK_SPEED_BONUS = Decimal("0.90")
    _R2_MOVEMENT_SPEED_BONUS = Decimal("0.40")
    _R2_HEAL_PER_SECOND = Decimal(125)

    def engagement_dash_distance(self, context: ParticipantContext) -> Decimal:
        """Expose Lunge's locked directional dash range.

        :param context: Role-bound snapshots for the current encounter.
        :return: Rank-independent Lunge distance in game units.
        """
        return Decimal(400)

    def engagement_speed_multiplier(self, context: ParticipantContext) -> Decimal:
        """Expose Grand Challenge's rank-two target-proximity speed bonus.

        :param context: Role-bound snapshots for the current encounter.
        :return: Movement-speed multiplier while near the challenged target.
        """
        return Decimal(1) + self._R2_MOVEMENT_SPEED_BONUS

    def item_candidate_blocker(self, item: dict[str, object]) -> str | None:
        """Reject item channels absent from Fiora's fixed duel model.

        AD, AP, attack speed, ability haste, health, resistances, penetration,
        movement, and tenacity reach modeled calculations or shared channels.

        :param item: Normalized candidate from the locked item catalog.
        :return: Fiora-scoped blocker, or ``None`` for represented channels.
        """
        stats = item["stats"]
        assert isinstance(stats, dict)
        unsupported = {
            "CRITICAL_STRIKE_CHANCE",
            "HEAL_SHIELD_POWER",
            "MANA",
            "MANA_REGEN",
        } & stats.keys()
        if unsupported:
            names = ",".join(sorted(unsupported))
            return f"FIORA_ITEM_STAT_NOT_MODELED:{item['id']}:{names}"
        return None

    @staticmethod
    def _haste_adjusted_ms(base_ms: int, ability_haste: Decimal) -> int:
        """Convert one cooldown through the standard ability-haste divisor.

        :param base_ms: Unmodified cooldown in milliseconds.
        :param ability_haste: Non-negative ability haste from the snapshot.
        :return: Deterministically rounded cooldown with a one-ms floor.
        """
        adjusted = Decimal(base_ms) * Decimal(100) / (Decimal(100) + ability_haste)
        return max(1, int(adjusted.to_integral_value()))

    @staticmethod
    def _vital_ratio(context: ParticipantContext) -> Decimal:
        """Calculate Duelist's Dance maximum-health true-damage ratio.

        :param context: Snapshot supplying Fiora's bonus attack damage.
        :return: Decimal fraction of the opponent's maximum health per vital.
        """
        return Decimal("0.03") + Decimal("0.0004") * context.snapshot.bonus_attack_damage

    @staticmethod
    def _vital_heal(context: ParticipantContext) -> Decimal:
        """Interpolate Duelist's Dance healing at the modeled champion level.

        :param context: Snapshot supplying Fiora's current level.
        :return: Raw self-healing generated by one vital hit.
        """
        return Decimal(35) + Decimal(65) * Decimal(context.snapshot.level - 1) / Decimal(17)

    def _vital_outputs(self, context: ParticipantContext) -> tuple:
        """Create one vital's true damage, healing, and movement status.

        :param context: Role-bound snapshots identifying both recipients.
        :return: Atomic outputs produced by one deterministic vital hit.
        """
        vital_damage = context.opponent_snapshot.max_hp * self._vital_ratio(context)
        return (
            damage(context.opponent_entity, vital_damage, DamageType.TRUE),
            healing(context.self_entity, self._vital_heal(context)),
            StatusOutput(context.self_entity, "FIORA_DUELIST_MOVEMENT_SPEED", 2000),
        )

    def _lunge_events(self, context: ParticipantContext) -> tuple[ActionEvent, ...]:
        """Schedule successful Q5 hits with the locked fifty-percent refund.

        :param context: Snapshot supplying bonus AD, haste, and duration.
        :return: Haste-sensitive Lunge events through the benchmark.
        """
        interval_ms = self._haste_adjusted_ms(3000, context.snapshot.ability_haste)
        raw_damage = Decimal(110) + Decimal("1.10") * context.snapshot.bonus_attack_damage
        base = self._sequence_base(context) + 100
        events: list[ActionEvent] = []
        at_ms = 200
        while at_ms <= context.duration_ms:
            outputs = [damage(context.opponent_entity, raw_damage, DamageType.PHYSICAL)]
            if not events:
                outputs.extend(self._vital_outputs(context))
            events.append(
                action(
                    f"FIORA_Q_LUNGE_{len(events) + 1}",
                    at_ms=at_ms,
                    sequence=base + len(events),
                    source=context.self_entity,
                    channel=ActionChannel.ABILITY,
                    outputs=tuple(outputs),
                )
            )
            at_ms += interval_ms
        return tuple(events)

    def _attack_events(self, context: ParticipantContext) -> tuple[ActionEvent, ...]:
        """Build E's reset pair, remaining vitals, and ordinary attacks.

        :param context: Snapshot supplying total AD, attack speed, and duration.
        :return: Blind-susceptible deterministic basic-attack events.
        """
        boosted_speed = (
            context.snapshot.attack_speed + self._ATTACK_SPEED_RATIO * self._E5_ATTACK_SPEED_BONUS
        )
        boosted_interval = self._attack_interval_ms(boosted_speed)
        normal_interval = self._attack_interval_ms(context.snapshot.attack_speed)
        shapes = [
            (900, "FIORA_BASIC_ATTACK_VITAL_2", context.snapshot.attack_damage, True, None),
            (1200, "FIORA_E_BLADEWORK_ATTACK_1", context.snapshot.attack_damage, True, "SLOW"),
            (
                1200 + boosted_interval,
                "FIORA_E_BLADEWORK_ATTACK_2",
                Decimal(2) * context.snapshot.attack_damage,
                True,
                None,
            ),
        ]
        at_ms = shapes[-1][0] + normal_interval
        attack_index = 1
        while at_ms <= context.duration_ms:
            shapes.append(
                (
                    at_ms,
                    f"FIORA_BASIC_ATTACK_{attack_index}",
                    context.snapshot.attack_damage,
                    False,
                    None,
                )
            )
            attack_index += 1
            at_ms += normal_interval

        base = self._sequence_base(context) + 200
        events: list[ActionEvent] = []
        for index, (at_ms, event_id, amount, vital, control) in enumerate(shapes):
            outputs = [damage(context.opponent_entity, amount, DamageType.PHYSICAL)]
            if control == "SLOW":
                outputs.append(
                    crowd_control(
                        context.opponent_entity, "SLOW", duration_ms=1000, magnitude=Decimal("0.30")
                    )
                )
            if vital:
                outputs.extend(self._vital_outputs(context))
            events.append(
                action(
                    event_id,
                    at_ms=at_ms,
                    sequence=base + index,
                    source=context.self_entity,
                    channel=ActionChannel.BASIC_ATTACK,
                    outputs=tuple(outputs),
                )
            )
        return tuple(events)

    def _ultimate_heal_events(
        self, context: ParticipantContext, *, completion_ms: int
    ) -> tuple[ActionEvent, ...]:
        """Schedule Grand Challenge's completed four-vital healing zone.

        :param context: Snapshot supplying Fiora's bonus attack damage.
        :param completion_ms: Timestamp of the fourth deterministic vital hit.
        :return: In-horizon one-second healing ticks after completion.
        """
        heal_per_tick = (
            self._R2_HEAL_PER_SECOND + Decimal("0.60") * context.snapshot.bonus_attack_damage
        )
        base = self._sequence_base(context) + 400
        events: list[ActionEvent] = []
        at_ms = completion_ms + 1000
        while at_ms <= min(completion_ms + 5000, context.duration_ms):
            events.append(
                action(
                    f"FIORA_R_GRAND_CHALLENGE_HEAL_{len(events) + 1}",
                    at_ms=at_ms,
                    sequence=base + len(events),
                    source=context.self_entity,
                    channel=ActionChannel.PASSIVE,
                    outputs=(healing(context.self_entity, heal_per_tick),),
                    requires_living_opponent=False,
                )
            )
            at_ms += 1000
        return tuple(events)

    def build_action_plan(self, context: ParticipantContext) -> ActionPlan:
        """Build Fiora's locked Q5/W1/E5/R2 level-13 duel sequence.

        :param context: Role-bound snapshots for Fiora and the opponent.
        :return: Q, W, E, R, vital, attack, and healing events with blockers.
        """
        base = self._sequence_base(context)
        attacks = self._attack_events(context)
        fourth_vital_ms = next(
            event.at_ms for event in attacks if event.id == "FIORA_E_BLADEWORK_ATTACK_2"
        )
        fixed_events = (
            action(
                "FIORA_R_GRAND_CHALLENGE_CAST",
                at_ms=0,
                sequence=base,
                source=context.self_entity,
                channel=ActionChannel.ABILITY,
                outputs=(StatusOutput(context.opponent_entity, "FIORA_R_CHALLENGED", 8000),),
            ),
            action(
                "FIORA_W_RIPOSTE_START",
                at_ms=2500,
                sequence=base + 1,
                source=context.self_entity,
                channel=ActionChannel.ABILITY,
                outputs=(StatusOutput(context.self_entity, "FIORA_W_PARRY", 750),),
                requires_living_opponent=False,
            ),
            action(
                "FIORA_W_RIPOSTE_STAB",
                at_ms=3250,
                sequence=base + 2,
                source=context.self_entity,
                channel=ActionChannel.ABILITY,
                outputs=(
                    damage(
                        context.opponent_entity,
                        Decimal(110) + context.snapshot.ability_power,
                        DamageType.MAGIC,
                    ),
                    crowd_control(
                        context.opponent_entity, "SLOW", duration_ms=2000, magnitude=Decimal("0.50")
                    ),
                ),
            ),
        )
        level_blockers = (
            ()
            if context.snapshot.level == 13
            else (f"FIORA_MODEL_LEVEL_UNSUPPORTED:{context.snapshot.level}",)
        )
        events = (
            *fixed_events,
            *self._lunge_events(context),
            *attacks,
            *self._ultimate_heal_events(context, completion_ms=fourth_vital_ms),
        )
        return ActionPlan(
            "fiora_q5_w1_e5_r2_level13_locked_v1",
            tuple(sorted(events, key=lambda event: (event.at_ms, event.sequence, event.id))),
            (
                *level_blockers,
                "FIORA_LEVEL13_Q5_W1_E5_R2_POLICY_UNVERIFIED",
                "FIORA_ROTATION_TIMING_UNVERIFIED",
                "FIORA_VITAL_DIRECTION_AND_POSITION_NOT_MODELED",
                "FIORA_Q_TARGET_SELECTION_AND_ON_HIT_INTERACTIONS_NOT_MODELED",
                "FIORA_Q_BLIND_AND_DODGE_INTERACTION_UNVERIFIED",
                "FIORA_W_REAL_CC_PARRY_TIMING_NOT_MODELED",
                "FIORA_W_ATTACK_SPEED_SLOW_NOT_MODELED",
                "FIORA_E_RESET_AND_ATTACK_TIMING_UNVERIFIED",
                "FIORA_R_MULTI_VITAL_MOVEMENT_SYNTHETIC",
                "FIORA_R_HEAL_ZONE_ALLY_EFFECTS_NOT_MODELED",
                "FIORA_RESOURCE_COSTS_NOT_EVALUATED",
            ),
        )

    def build_reaction_plan(self, context: ParticipantContext) -> ReactionPlan:
        """Expose fixed Riposte immunity and the modeled slow outcomes.

        :param context: Role-bound snapshots for the Fiora participant.
        :return: Damage, control-immunity, and opponent movement-block windows.
        """
        return ReactionPlan(
            "fiora_w1_e5_riposte_reaction_v1",
            damage_windows=(
                DamageModifierWindow(
                    "fiora_w_riposte_damage_immunity",
                    2500,
                    min(3250, context.duration_ms),
                    context.self_entity,
                    (DamageType.PHYSICAL, DamageType.MAGIC, DamageType.TRUE),
                    Decimal(0),
                ),
            ),
            cast_block_windows=(
                CastBlockWindow(
                    "fiora_e_first_attack_slow",
                    1200,
                    min(2200, context.duration_ms),
                    (ActionChannel.MOVEMENT,),
                    "FIORA_E_BLADEWORK_ATTACK_1",
                    True,
                    ControlType.SLOW,
                ),
                CastBlockWindow(
                    "fiora_w_stab_slow",
                    3250,
                    min(5250, context.duration_ms),
                    (ActionChannel.MOVEMENT,),
                    "FIORA_W_RIPOSTE_STAB",
                    True,
                    ControlType.SLOW,
                ),
            ),
            control_immunity_windows=(
                ControlImmunityWindow(
                    "fiora_w_riposte_control_immunity",
                    2500,
                    min(3250, context.duration_ms),
                    context.self_entity,
                    (ControlType.ALL,),
                    "FIORA_W_RIPOSTE_START",
                ),
            ),
            blockers=(
                "FIORA_W_REAL_CC_PARRY_TIMING_NOT_MODELED",
                "FIORA_W_STUN_VARIANT_NOT_MODELED",
                "FIORA_W_DEBUFF_CLEANSE_SEMANTICS_NOT_MODELED",
            ),
        )
